### ISSUE TITLE
Unable to "Pack .paks to Mods folder instead of zipping"

### ISSUE THREAD

**Issue by SoggyBurritoVR** [ShinyHobo/BG3-Modders-Multitool#318]
Hello, 

I am unfortunately not able to use the specified feature.

Getting the following error:

"Failed to move (MODNAME) pak to Mods folder. Is the game running?"

The game is not running, tried removing the same named pak from my mods folder as well but no change.  Tried multiple mods, plus running in Administrator mode.

Let me know if I can provide any logs to help diagnose this issue.

**Comment by ShinyHobo** [comment]
This happens when either the file exists and is in use, the directory can't be written to, or the pak is failing to build (isn't in your Temp directory at the time it is trying to move the pak). I would suggest rebooting to see if that fixes the issue. I have uploaded a new version of 0.12.20 that has alternate logging messages for this issue. Try it and copy the error here.

**Comment by SoggyBurritoVR** [comment]
Error: (17) The system cannot move the file to a different disk drive: [C:\Users\Ori\AppData\Local\Temp\BG3ModPacker\(MODNAME).pak]

**Comment by ShinyHobo** [comment]
Are you using the symlink path or the actual path? I would suggest using the actual path if you aren't already.

**Comment by ShinyHobo** [comment]
Fixed in v0.12.20b
