### ISSUE TITLE
Armor visuals disappear when repacking with Multitool

### ISSUE THREAD

**Issue by robogena** [ShinyHobo/BG3-Modders-Multitool#334]
Hi ShinyHobo! I’m having an issue with armor visuals disappearing when repacking a mod. From my testing, the problem doesn’t seem to be with the mod itself. If I repack with Multitool, the visuals disappear. If I repack with LSLib, the visuals are there.

**My versions:**
BG3 DX 11, Patch 6 Hotfix 20, v4.1.1.4854838
[SR Apparel v2.1.0](https://www.nexusmods.com/baldursgate3/mods/6895)
Modder’s Multitool v0.12.26
LSLib v1.19.3
Baldur’s Gate 3 Mod Manager v1.0.10.0

**How to reproduce:**
1. Create a save file with SR Apparel v2.1.0 loaded. (Only v2.1.0 is available to DL but I can reproduce this on v2.0.0 too.)
2. Confirm visuals are present, which are currently: body type 1, body type 3 and githyanki F.
3. Unpack the mod with LSLIb.
4. Repack with Modder’s Multitool using default values (Priority 30, with compression) directly to mod folder. Reimport mod list with BG3MM.
5. Open save file. Visuals are now missing for all body types.
6. Repack with LSLib using default values (Version V18, Compression LZ4, Priority 0). Replace in mod folder. Reimport mod list with BG3MM.
7. Open save file. Visuals are present again.

I tested with mod fixer included vs removed, with LSLib Priority 0 vs Priority 30, with package changes vs unchanged, etc. and the only thing that seems to remove the visuals is being packed with Multitool. I have no idea what would cause this… BUT I did see that under Generated>Public>SR_Apparel>Assets, there is a desktop.ini file which contains:
```
[LocalizedFileNames]
HUM_F_CLT_Rich_Dress_B_Footwear_MSKcloth.DDS=@HUM_F_CLT_Rich_Dress_B_Footwear_MSKcloth.DDS,0
```
My modding skills are super basic, so I don’t know if ini files are typically included in mods? (haven’t seen one in a mod before this) Or if this is something Multitool is even meant to handle?

**Comment by ShinyHobo** [comment]
It sounds like you aren't using the multitool correctly. If you use it, you must unpack with it in order to re-pack with it, to ensure organizational integrity. Doing it the way you described (lslib => multitool) produces a smaller pak. Doing it with multitool for both steps results in the same size pak.

This author is incorrectly using .lsx files with the same name as .lsf files to keep notes, something that only lslib on its own supports. My wiki states that both .lsf and .lsx files with the same name should not be in the same directory because one will be ignored.

**Comment by robogena** [comment]
> It sounds like you aren't using the multitool correctly.

Omg, I sure am not 😳 It makes sense, but I had no idea criss-crossing packing tools could be a problem. I'm surprised it took me this long to break something!

Thank you for such a speedy answer!
