### ISSUE TITLE
Unable to unpack textures.pak

### ISSUE THREAD

**Issue by RoraBeth** [ShinyHobo/BG3-Modders-Multitool#350]
Attempting to unpack textures gives the following error

"Error unpacking Textures: LZ4 block is corrupted, or invalid length has been given."

Unpacking all other .pak files appears to have worked however 

I thought maybe it was something with my game install so I tried verifying files and had no luck.

**Comment by ShinyHobo** [comment]
After some investigation, this is a bug with LSLib. I am unable to determine what the issue is; a clean version of lslib manually built has the same issue, but norbyte's release does not. As a work around while I investigate, please use LSLib's ConverterApp if you need to extract the whole Textures.pak.

**Comment by RoraBeth** [comment]
Thanks so much for the info!

**Comment by ShinyHobo** [comment]
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/6206737/e059896c-b61a-4877-8ce3-26263af47780)
I can confirm that previews and extractions that stopped working work again.
